name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Check out the repo
       uses: actions/checkout@v4
    
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '18'

     - name: Install Angular CLI
       run: npm install -g @angular/cli@18 #replace with your angular version
    
     - name: Install Angular dependencies
       working-directory: fountainpensng.client
       run: npm install
           
     - name: Build Angular app
       working-directory: fountainpensng.client
       run: npm run build

     - name: Build and push angular app Docker image
       uses: docker/build-push-action@v6
       env:
         DATABASE_URL: "postgresql://localhost:9999/placeholder"
       with:
         context: ./fountainpensng.client
         file: ./fountainpensng.client/Dockerfile
         push: true
         tags: adamsarok/fountainpens-ng-cl:latest

     - name: Setup .NET SDK
       uses: actions/setup-dotnet@v3
       with:
        dotnet-version: 9.0

     - name: Build API
       working-directory: ./FountainPensNg.Server
       env:
        DATABASE_URL: "postgresql://localhost:9999/placeholder"
       run: dotnet build

     - name: Run tests with coverage
       working-directory: ./FountainPensNg.xTests
       run: dotnet test --configuration Release --collect:"XPlat Code Coverage"

     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v5
       with:
         token: ${{ secrets.CODECOV_TOKEN }}

     - name: Build and push API Docker image
       uses: docker/build-push-action@v6
       env:
         DATABASE_URL: "postgresql://localhost:9999/placeholder"
       with:
         context: ./FountainPensNg.Server
         file: ./FountainPensNg.Server/Dockerfile
         push: true
         tags: adamsarok/fountainpens-api:latest
